baseURL: "https://summerhan16.github.io/"
languageCode: "en-us"
title: "Summer's Archive"
theme: "PaperMod"
pagination:
  pagerSize: 5

params:

  homeInfoParams:
    Title: "시작"
    Content: "첫시작."

  ShowBreadCrumbs: true
  ShowReadingTime: true
  defaultTheme: light
  disableThemeToggle: true
  ShowMenu: true
  ShowHomeContent: true

  assets:
    disableFingerprinting: true
  
  footer:
    text: "© 2025 Summer Han. All rights reserved.迂遠."

  mainSections: ["posts"]

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 0

    - identifier: paper-review
      name: Paper Review
      url: /categories/paper-review/
      weight: 1

    - identifier: code
      name: Code
      url: /categories/code/
      weight: 2
    
    - identifier: til
      name: TIL
      url: /categories/til/
      weight: 3

    - identifier: life
      name: Life
      url: /categories/life/
      weight: 4

    - identifier: search
      name: Search
      url: /categories/search/
      weight: 5

    - identifier: tags
      name: Tags
      url: /tags/
      weight: 6
